import type {
  AcademyOverviewStats,
  AcademyBranch,
  AcademyStudent,
  AcademyCoachMember,
  AcademyBatch,
  AcademyProgram,
  AcademyGradingEvent,
  AcademyAchievement,
  AcademyReviewItem,
} from "./types";

export const SAMPLE_ACADEMY_STATS: AcademyOverviewStats = {
  totalStudents: 248,
  activeCoaches: 12,
  upcomingClasses: 6,
  upcomingGradings: 2,
  upcomingTournaments: 3,
  activeBookings: 28,
  revenueThisMonth: "₹3,42,000",
  averageRating: 4.92,
  totalReviews: 84,
};

export const SAMPLE_ACADEMY_BRANCHES: AcademyBranch[] = [
  {
    id: "branch-1",
    name: "Main Dojo & High Performance Center",
    address: "Plot 42, Sector 18, Sports Enclave",
    city: "Mumbai",
    contactPhone: "+91 98201 12345",
    contactEmail: "maindojo@lordofsportz.com",
    sports: ["Karate", "Martial Arts & Self-Defense"],
    coaches: ["Shihan Rajiv Sharma (5th Dan)", "Sensei Pooja Rao (3rd Dan)"],
    facilities: ["Tatami Mats Hall", "Strength & Conditioning Gym", "Changing Rooms", "First Aid Station"],
    timings: "Mon-Sat: 6:00 AM - 9:00 PM",
    isMainBranch: true,
  },
  {
    id: "branch-2",
    name: "West Branch Arena",
    address: "Bandra Sports Complex, Linking Road",
    city: "Mumbai",
    contactPhone: "+91 98201 54321",
    contactEmail: "bandra@lordofsportz.com",
    sports: ["Karate", "Junior Self-Defense"],
    coaches: ["Sensei Pooja Rao", "Sensei Amit Deshmukh (2nd Dan)"],
    facilities: ["Training Hall", "Equipment Storage", "Spectator Seating"],
    timings: "Mon-Fri: 7:00 AM - 8:00 PM, Sat: 8:00 AM - 1:00 PM",
    isMainBranch: false,
  },
  {
    id: "branch-3",
    name: "Thane Youth Academy",
    address: "Ghobunder Road, Olympic Center",
    city: "Thane",
    contactPhone: "+91 98201 99887",
    contactEmail: "thane@lordofsportz.com",
    sports: ["Karate", "Taekwondo"],
    coaches: ["Sensei Amit Deshmukh"],
    facilities: ["Dojo Hall", "Parking", "Parent Lounge"],
    timings: "Tue-Sun: 7:00 AM - 7:30 PM",
    isMainBranch: false,
  },
];

export const SAMPLE_ACADEMY_COACHES: AcademyCoachMember[] = [
  {
    id: "coach-1",
    name: "Shihan Rajiv Sharma",
    title: "Chief Technical Director & Head Instructor",
    sports: ["Karate"],
    disciplines: ["Shotokan", "Kumite", "Kata Mastery"],
    experienceYears: 18,
    assignedBranches: ["Main Dojo", "West Branch"],
    phone: "+91 98201 11223",
    email: "rajiv.sharma@lordofsportz.com",
  },
  {
    id: "coach-2",
    name: "Sensei Pooja Rao",
    title: "Senior Kata Instructor",
    sports: ["Karate"],
    disciplines: ["Shotokan Kata", "Bunkai Application"],
    experienceYears: 9,
    assignedBranches: ["Main Dojo", "West Branch"],
    phone: "+91 98201 44556",
    email: "pooja.rao@lordofsportz.com",
  },
  {
    id: "coach-3",
    name: "Sensei Amit Deshmukh",
    title: "Kumite Competition Coach",
    sports: ["Karate"],
    disciplines: ["Competitive Kumite", "Youth Conditioning"],
    experienceYears: 7,
    assignedBranches: ["West Branch", "Thane Youth Academy"],
    phone: "+91 98201 77889",
    email: "amit.deshmukh@lordofsportz.com",
  },
];

export const SAMPLE_ACADEMY_STUDENTS: AcademyStudent[] = [
  {
    id: "stu-1",
    name: "Aarav Mehta",
    gender: "MALE",
    age: 14,
    dateOfBirth: "2012-04-12",
    beltRank: 7,
    beltName: "3rd Kyu",
    beltColor: "#92400e",
    branchName: "Main Dojo",
    batchName: "Cadet Advanced Squad",
    joinedOn: "2022-01-15",
    attendanceRate: 96,
    status: "ACTIVE",
  },
  {
    id: "stu-2",
    name: "Ananya Iyer",
    gender: "FEMALE",
    age: 16,
    dateOfBirth: "2010-09-24",
    beltRank: 9,
    beltName: "1st Kyu (Brown)",
    beltColor: "#451a03",
    branchName: "Main Dojo",
    batchName: "Dan Exam Preparatory",
    joinedOn: "2020-08-10",
    attendanceRate: 98,
    status: "ACTIVE",
  },
  {
    id: "stu-3",
    name: "Kabir Verma",
    gender: "MALE",
    age: 10,
    dateOfBirth: "2016-02-18",
    beltRank: 4,
    beltName: "6th Kyu (Green)",
    beltColor: "#16a34a",
    branchName: "West Branch",
    batchName: "Junior Intermediate",
    joinedOn: "2023-06-01",
    attendanceRate: 92,
    status: "ACTIVE",
  },
  {
    id: "stu-4",
    name: "Rhea Kulkarni",
    gender: "FEMALE",
    age: 12,
    dateOfBirth: "2014-11-05",
    beltRank: 5,
    beltName: "5th Kyu (Blue)",
    beltColor: "#2563eb",
    branchName: "Thane Youth Academy",
    batchName: "Youth Kumite Batches",
    joinedOn: "2023-03-20",
    attendanceRate: 88,
    status: "ACTIVE",
  },
  {
    id: "stu-5",
    name: "Vikram Singhania",
    gender: "MALE",
    age: 18,
    dateOfBirth: "2008-01-10",
    beltRank: 10,
    beltName: "1st Dan (Shodan - Black)",
    beltColor: "#000000",
    branchName: "Main Dojo",
    batchName: "Senior Black Belt Squad",
    joinedOn: "2018-05-12",
    attendanceRate: 100,
    status: "ACTIVE",
  },
];

export const SAMPLE_ACADEMY_PROGRAMS: AcademyProgram[] = [
  {
    id: "prog-1",
    name: "Karate Foundation & Belt Journey",
    sport: "Karate",
    discipline: "Shotokan Karate",
    level: "BEGINNER",
    description: "Core stances, fundamental punches (Zuki), kicks (Geri), and basic Kata for 9th to 6th Kyu.",
    monthlyFee: 2500,
    durationMonths: 12,
  },
  {
    id: "prog-2",
    name: "Intermediate Technical Program",
    sport: "Karate",
    discipline: "Shotokan & Kumite Basics",
    level: "INTERMEDIATE",
    description: "Complex Kata (Heian series), controlled sparring (Yakusoku Kumite), and conditioning.",
    monthlyFee: 3200,
    durationMonths: 12,
  },
  {
    id: "prog-3",
    name: "Elite National Competitive Squad",
    sport: "Karate",
    discipline: "WKF Kumite & Advanced Kata",
    level: "ADVANCED",
    description: "High-intensity tournament training, tactical bout strategy, electronic scoring drill simulations.",
    monthlyFee: 4500,
    durationMonths: 24,
  },
];

export const SAMPLE_ACADEMY_BATCHES: AcademyBatch[] = [
  {
    id: "batch-1",
    name: "Morning Tigers (Beginner)",
    program: "Karate Foundation",
    branch: "Main Dojo",
    coach: "Shihan Rajiv Sharma",
    days: ["Monday", "Wednesday", "Friday"],
    startTime: "06:30",
    endTime: "07:45",
    capacity: 25,
    enrolled: 22,
    ageGroup: "6 - 12 Years",
  },
  {
    id: "batch-2",
    name: "Evening Warriors (Cadet & Youth)",
    program: "Intermediate Technical Program",
    branch: "Main Dojo",
    coach: "Sensei Pooja Rao",
    days: ["Tuesday", "Thursday", "Saturday"],
    startTime: "17:30",
    endTime: "19:00",
    capacity: 25,
    enrolled: 24,
    ageGroup: "12 - 17 Years",
  },
  {
    id: "batch-3",
    name: "Weekend Competition Dojo",
    program: "Elite National Competitive Squad",
    branch: "West Branch Arena",
    coach: "Sensei Amit Deshmukh",
    days: ["Saturday", "Sunday"],
    startTime: "08:00",
    endTime: "10:30",
    capacity: 20,
    enrolled: 18,
    ageGroup: "14+ Years (Competitive)",
  },
];

export const SAMPLE_ACADEMY_GRADINGS: AcademyGradingEvent[] = [
  {
    id: "grade-1",
    title: "Winter Kyu Belt Promotion Examination 2026",
    sport: "Karate",
    targetBelt: "Yellow, Orange, Green & Blue",
    targetGrade: "8th to 5th Kyu",
    eventDate: "2026-11-15",
    examiner: "Shihan Rajiv Sharma & Board of Examiners",
    eligibleCount: 42,
    location: "Main Dojo Tatami Hall",
    status: "UPCOMING",
  },
  {
    id: "grade-2",
    title: "Senior Brown & Black Belt National Grading",
    sport: "Karate",
    targetBelt: "Brown 1st Kyu & Shodan 1st Dan",
    targetGrade: "1st Kyu to 1st Dan",
    eventDate: "2026-12-20",
    examiner: "All India Karate Federation Technical Commission",
    eligibleCount: 14,
    location: "State Martial Arts Gymnasium",
    status: "UPCOMING",
  },
];

export const SAMPLE_ACADEMY_ACHIEVEMENTS: AcademyAchievement[] = [
  {
    id: "ach-1",
    title: "All India National Karate Championship 2025",
    category: "CHAMPIONSHIP",
    role: "STUDENT_SQUAD",
    year: 2025,
    level: "NATIONAL",
    description: "Overall Team Champions with 8 Gold, 6 Silver, and 11 Bronze medals across Kata and Kumite.",
  },
  {
    id: "ach-2",
    title: "Best Martial Arts Training Academy of the Year",
    category: "FEDERATION_AWARD",
    role: "ACADEMY",
    year: 2025,
    level: "STATE",
    description: "Awarded by State Sports Development Authority for youth athletic development and fair play excellence.",
  },
  {
    id: "ach-3",
    title: "Commonwealth Karate Championship - Silver Medal",
    category: "MEDAL",
    role: "COACH",
    year: 2024,
    level: "INTERNATIONAL",
    description: "Mentored athlete Priya Nair to -55kg Female Kumite Silver Medal.",
  },
];

export const SAMPLE_ACADEMY_REVIEWS: AcademyReviewItem[] = [
  {
    id: "rev-1",
    author: "Dr. Sandeep Mehta (Parent)",
    role: "PARENT",
    rating: 5,
    date: "2026-09-12",
    comment:
      "My son has trained under Shihan Rajiv for three years. The discipline, physical stamina, and traditional values taught here are world-class. The branch management and attendance alerts on LordOfSportz make communication effortless.",
    reply: {
      text: "Thank you Dr. Mehta! Aarav is a model athlete in our cadet squad. We look forward to his upcoming grading exam.",
      repliedAt: "2026-09-13",
    },
  },
  {
    id: "rev-2",
    author: "Ananya Iyer (Senior Student)",
    role: "STUDENT",
    rating: 5,
    date: "2026-08-28",
    comment:
      "The competitive coaching here is rigorous and technical. The sparring drills, tournament travel support, and electronic timing equipment prepared me for nationals. Best academy in the city.",
  },
];
